In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Customer-Churn-Records.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [3]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Card Type', 'Point Earned'],
      dtype='str')

In [4]:
df_clean = df.drop(columns=["RowNumber", "CustomerId", "Surname"])

df_clean["Churn Status"] = df_clean["Exited"].map({
    1: "Churned",
    0: "Retained"
})

df_clean["Complaint Status"] = df_clean["Complain"].map({
    1: "Complained",
    0: "No Complaint"
})

df_clean["Active Status"] = df_clean["IsActiveMember"].map({
    1: "Active",
    0: "Inactive"
})

df_clean["Credit Card Status"] = df_clean["HasCrCard"].map({
    1: "Has Credit Card",
    0: "No Credit Card"
})

df_clean["Age Group"] = pd.cut(
    df_clean["Age"],
    bins=[0, 30, 45, 60, 100],
    labels=["Under 30", "30-45", "46-60", "60+"]
)

df_clean["Balance Group"] = pd.cut(
    df_clean["Balance"],
    bins=[-1, 0, 50000, 150000, 300000],
    labels=["No Balance", "Low Balance", "Medium Balance", "High Balance"]
)

df_clean["Credit Score Group"] = pd.cut(
    df_clean["CreditScore"],
    bins=[0, 580, 670, 740, 850],
    labels=["Poor", "Fair", "Good", "Excellent"]
)

df_clean.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,...,Satisfaction Score,Card Type,Point Earned,Churn Status,Complaint Status,Active Status,Credit Card Status,Age Group,Balance Group,Credit Score Group
0,619,France,Female,42,2,0.00,1,1,1,101348.88,...,2,DIAMOND,464,Churned,Complained,Active,Has Credit Card,30-45,No Balance,Fair
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,...,3,DIAMOND,456,Retained,Complained,Active,No Credit Card,30-45,Medium Balance,Fair
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,...,3,DIAMOND,377,Churned,Complained,Inactive,Has Credit Card,30-45,High Balance,Poor
3,699,France,Female,39,1,0.00,2,0,0,93826.63,...,5,GOLD,350,Retained,No Complaint,Inactive,No Credit Card,30-45,No Balance,Good
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,...,5,GOLD,425,Retained,No Complaint,Active,Has Credit Card,30-45,Medium Balance,Excellent

In [5]:
df_clean.to_csv("cleaned_customer_churn.csv", index=False)

In [6]:
df_clean.shape

(10000, 22)